/* Steps 3-35 UI: focused implementation, preserving the existing app shell. */
(function(){
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function F(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};const ut=localStorage.getItem('ludo_user_token');const at=localStorage.getItem('lb_admin_token');if(ut)h.Authorization='Bearer '+ut;if(at)h.Authorization='Bearer '+at;const r=await fetch(path,{...opt,headers:h});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');return j}
window.quickOpen=function(id,name,icon){
 if(id==='deposit'){selectedId='deposit';openDeposit();return} if(id==='withdraw'){selectedId='withdraw';openWithdraw();return} if(id==='statement'){selectedId='statement';openStatement();return}
 const map={match:showMatches,mymatch:showMyMatches,notifications:showNotifications,support:showSupport,referral:showReferral,leaderboard:showLeaderboard}; if(map[id]){map[id]();return}
 const found=(window.all||[]).find(x=>x.id===id);if(found){const box=[...document.querySelectorAll('.cat')].find(x=>x.textContent.trim()===found.name);show(found,box);return}
};
window.showMatches=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🎮 Matches</h3><div id="matchList">Loading...</div>';try{const j=await F('/api/user/matches');v.querySelector('#matchList').innerHTML=(j.matches||[]).map(m=>`<div class="item"><b>${E(m.title)}</b><div>Entry: ৳${Number(m.entry_fee).toFixed(2)} • Prize: ৳${Number(m.winning_amount).toFixed(2)} • ${m.players?.length||0}/${m.max_players}</div><div>${E(new Date(m.scheduled_at).toLocaleString())}</div><button class="btn" onclick="joinUserMatch('${E(m.id)}')">Join Match</button></div>`).join('')||'<p>No matches available.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};
window.joinUserMatch=async function(id){try{const j=await F('/api/user/matches/'+encodeURIComponent(id)+'/join',{method:'POST'});alert(j.message||'Joined');await refreshDashboard();showMatches()}catch(e){alert(e.message)}};
window.showMyMatches=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🎯 My Matches</h3><div id="mine">Loading...</div>';try{const j=await F('/api/user/matches/mine');v.querySelector('#mine').innerHTML=(j.matches||[]).map(m=>`<div class="item"><b>${E(m.title)}</b><div>Slot: ${m.my_slot||'-'} • Status: ${E(m.status)}</div><div>Room: ${m.room_id?E(m.room_id):'Not published yet'} ${m.room_password?' / '+E(m.room_password):''}</div><div>Result: ${m.winner_user_id?'Winner selected':'Pending'}</div></div>`).join('')||'<p>No joined matches.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};
window.showNotifications=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🔔 Notifications</h3><button class="btn" onclick="readAllNotifications()">Mark all read</button><div id="notices">Loading...</div>';try{const j=await F('/api/user/notifications');v.querySelector('#notices').innerHTML=(j.notifications||[]).map(n=>`<div class="item"><b>${E(n.title)}</b><div>${E(n.message)}</div><small>${E(new Date(n.created_at).toLocaleString())} ${n.read_at?'':'• UNREAD'}</small></div>`).join('')||'<p>No notifications.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};
window.readAllNotifications=async function(){await F('/api/user/notifications/read',{method:'POST',body:JSON.stringify({id:'all'})});showNotifications()};
window.showSupport=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>💬 Customer Support</h3><div id="supportMsgs">Loading...</div><textarea id="supportText" placeholder="আপনার সমস্যা লিখুন"></textarea><button class="btn" onclick="sendSupport()">Send</button>';try{const j=await F('/api/user/support');v.querySelector('#supportMsgs').innerHTML=(j.messages||[]).map(n=>`<div class="item"><b>${E(n.sender)}</b><div>${E(n.message)}</div></div>`).join('')||'<p>No messages yet.</p>'}catch(e){}};
window.sendSupport=async function(){const t=document.getElementById('supportText');if(!t.value.trim())return;try{await F('/api/user/support',{method:'POST',body:JSON.stringify({message:t.value})});showSupport()}catch(e){alert(e.message)}};
window.showReferral=async function(){if(!authToken()){openAuth();return}const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🔗 Referral</h3><div id="ref">Loading...</div>';try{const j=await F('/api/user/referral');v.querySelector('#ref').innerHTML=j.enabled?`<div class="item"><b>Your Referral Code</b><div style="font-size:24px">${E(j.code)}</div><p>Bonus: ৳${Number(j.bonus).toFixed(2)}</p></div>`:'<p>Referral system is currently disabled.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};

window.showLeaderboard=async function(){const v=document.getElementById('view');v.classList.add('show');v.innerHTML='<h3>🏆 Leaderboard</h3><div id="leaderboardList">Loading...</div>';try{const j=await F('/api/leaderboard');v.querySelector('#leaderboardList').innerHTML=(j.leaderboard||[]).map(x=>`<div class="item"><b>#${x.rank} ${E(x.user_code)}</b><span>${x.wins} Wins • ৳${Number(x.prize||0).toFixed(2)}</span></div>`).join('')||'<p>No leaderboard data yet.</p>'}catch(e){v.innerHTML+='<p class="err">'+E(e.message)+'</p>'}};

if(typeof window.screenFor==='function'){
 const old=window.screenFor; window.screenFor=function(x){const id=x.id;
  if(id==='payment-methods')return adminPaymentMethods(); if(['match-create','match-list','match-schedule','room-id-management','prize-approval'].includes(id))return adminMatches(id); if(id==='withdrawal-management')return adminWithdrawals();
  if(['user-management','total-users','active-users','user-block-unblock','user-balance-management'].includes(id))return adminUsers();
  if(id==='reports')return adminReports(); if(id==='audit-log')return adminAudit(); if(id==='admin-roles')return adminRoles(); if(id==='banner-management')return adminBanners(); if(id==='faq-management')return adminFaqs(); if(id==='rules-management')return adminPages(); if(id==='support-management')return adminSupport(); if(id==='notifications')return adminNotice(); if(id==='website-tools')return adminWebsiteTools();
  return old(x);
 };
}
window.adminPaymentMethods=function(){setTimeout(loadPM,0);return '<h1 class="page-title">Payment Methods</h1><p class="subtitle">User Deposit screen-এর Payment Method, নাম, নম্বর, Logo ও instructions এখান থেকে পরিবর্তন করতে পারবেন।</p><div class="panel"><div id="pmBox">Loading...</div></div>'};
async function loadPM(){const b=document.getElementById('pmBox');if(!b)return;const j=await F('/api/admin/payment-methods');b.innerHTML=(j.methods||[]).map(m=>`<div class="option-row" style="align-items:flex-start;flex-wrap:wrap"><div class="mini">${m.logo?`<img src="${E(m.logo)}">`:'💳'}</div><div style="flex:1;min-width:260px"><div class="settings-grid"><div class="field"><label>Method Name</label><input id="pmname-${m.id}" value="${E(m.name)}"></div><div class="field"><label>Payment Number</label><input id="pmn-${m.id}" inputmode="numeric" value="${E(m.number||'')}"></div><div class="field"><label>Account Name</label><input id="pma-${m.id}" value="${E(m.account_name||'')}"></div><div class="field"><label>Minimum Deposit</label><input id="pmin-${m.id}" type="number" value="${Number(m.min_deposit||0)}"></div><div class="field"><label>Maximum Deposit</label><input id="pmax-${m.id}" type="number" value="${Number(m.max_deposit||1000000)}"></div><div class="field"><label>Logo URL / File path</label><input id="pmurl-${m.id}" value="${E(m.logo||'')}"></div><div class="field wide"><label>Instructions</label><textarea id="pmi-${m.id}">${E(m.instructions||'')}</textarea></div><div class="field"><label>Change Logo</label><input id="pmfile-${m.id}" type="file" accept="image/*"></div></div><label><input id="pme-${m.id}" type="checkbox" ${m.enabled?'checked':''}> Enabled</label> <button class="btn green" onclick="savePM('${m.id}')">💾 Save</button></div></div>`).join('')};
window.savePM=async id=>{const file=document.getElementById('pmfile-'+id)?.files?.[0];const logo=file?await file64(file):(document.getElementById('pmurl-'+id).value.trim());await F('/api/admin/payment-methods/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({name:document.getElementById('pmname-'+id).value.trim(),number:document.getElementById('pmn-'+id).value.trim(),account_name:document.getElementById('pma-'+id).value.trim(),min_deposit:Number(document.getElementById('pmin-'+id).value||0),max_deposit:Number(document.getElementById('pmax-'+id).value||1000000),instructions:document.getElementById('pmi-'+id).value,logo,enabled:document.getElementById('pme-'+id).checked})});alert('Payment Method Saved');loadPM()};
window.adminMatches=function(id){setTimeout(()=>loadAM(id),0);return '<h1 class="page-title">'+E(id==='match-create'?'Match Create':id==='match-schedule'?'Match Schedule':id==='room-id-management'?'Room ID Management':id==='prize-approval'?'Prize Approval':'Match List')+'</h1><div class="panel"><div id="amBox">Loading...</div></div>'};
async function loadAM(id){const b=document.getElementById('amBox');if(!b)return;let j=await F('/api/admin/matches');if(id==='match-create')b.innerHTML='<div class="settings-grid"><input id="mtTitle" placeholder="Match title"><input id="mtFee" type="number" placeholder="Entry fee"><input id="mtPrize" type="number" placeholder="Prize"><input id="mtPlayers" type="number" value="4" placeholder="Players"><input id="mtDate" type="datetime-local"><textarea id="mtRules" placeholder="Rules"></textarea></div><button class="btn green" onclick="createAM()">Create Match</button>'+renderMatches(j.matches);else b.innerHTML=renderMatches(j.matches,id)}
function renderMatches(a,id){return (a||[]).map(m=>`<div class="item"><b>${E(m.title)} (#${E(m.match_code)})</b><div>৳${Number(m.entry_fee).toFixed(2)} / Prize ৳${Number(m.winning_amount).toFixed(2)} • ${m.players?.length||0}/${m.max_players} • ${E(m.status)}</div><div>Room: ${E(m.room_id||'-')} ${m.room_password?'/ '+E(m.room_password):''}</div>${id==='room-id-management'?`<button class="btn" onclick="setRoom('${E(m.id)}')">Set Room</button>`:''}${id==='prize-approval'?`<button class="btn green" onclick="prize('${E(m.id)}')">Approve Prize</button>`:''}${id==='match-list'?`<button class="btn" onclick="setWinner('${E(m.id)}')">Set Winner</button><button class="btn red" onclick="cancelAM('${E(m.id)}')">Cancel/Refund</button><button class="btn red" onclick="deleteAM('${E(m.id)}')">Delete</button>`:''}</div>`).join('')||'<p>No matches.</p>'}
window.createAM=async()=>{await F('/api/admin/matches',{method:'POST',body:JSON.stringify({title:mtTitle.value,entry_fee:mtFee.value,winning_amount:mtPrize.value,max_players:mtPlayers.value,scheduled_at:mtDate.value?new Date(mtDate.value).toISOString():new Date().toISOString(),rules:mtRules.value})});alert('Match created');loadAM('match-create')};
window.setWinner=async id=>{const u=prompt('Winner User ID');if(!u)return;await F('/api/admin/matches/'+id+'/winner',{method:'POST',body:JSON.stringify({user_id:u})});alert('Winner selected');loadAM('match-list')};window.cancelAM=async id=>{if(confirm('Cancel match and refund all joined players?')){await F('/api/admin/matches/'+id+'/cancel',{method:'POST'});alert('Cancelled and refunded');loadAM('match-list')}};
window.setRoom=async id=>{const r=prompt('Room ID',''),p=prompt('Room Password','');if(r===null||p===null)return;await F('/api/admin/matches/'+id+'/room',{method:'POST',body:JSON.stringify({room_id:r,room_password:p})});loadAM('room-id-management')};
window.prize=async id=>{await F('/api/admin/matches/'+id+'/prize',{method:'POST'});alert('Prize approved');loadAM('prize-approval')};window.deleteAM=async id=>{if(confirm('Delete match?')){await F('/api/admin/matches/'+id,{method:'DELETE'});loadAM('match-list')}};
window.adminUsers=function(){setTimeout(loadUsers,0);return '<h1 class="page-title">User Management</h1><div class="panel"><input id="userSearch" placeholder="Search user / phone"><button class="btn" onclick="loadUsers()">Search</button><div id="usersBox">Loading...</div></div>'};
async function loadUsers(){const b=document.getElementById('usersBox');if(!b)return;const j=await F('/api/admin/users?q='+encodeURIComponent(document.getElementById('userSearch')?.value||''));b.innerHTML=(j.users||[]).map(u=>`<div class="item"><b>${E(u.user_code)}</b> ${E(u.name||'')}<div>${E(u.phone)} • ${E(u.status)} • Gaming ৳${Number(u.gaming_balance).toFixed(2)} • Winning ৳${Number(u.winning_balance).toFixed(2)}</div><button class="btn" onclick="toggleUser('${E(u.id)}','${u.status==='active'?'blocked':'active'}')">${u.status==='active'?'Block':'Unblock'}</button><button class="btn" onclick="adjustUser('${E(u.id)}','gaming')">Gaming ±</button><button class="btn" onclick="adjustUser('${E(u.id)}','winning')">Winning ±</button></div>`).join('')||'<p>No users.</p>'};
window.toggleUser=async(id,status)=>{await F('/api/admin/users/'+id+'/status',{method:'POST',body:JSON.stringify({status})});loadUsers()};window.adjustUser=async(id,type)=>{const a=prompt('Amount (+ add / - deduct)','0');if(a===null)return;await F('/api/admin/users/'+id+'/balance',{method:'POST',body:JSON.stringify({balance_type:type,amount:Number(a),note:'Admin adjustment'})});loadUsers()};
window.adminReports=function(){setTimeout(loadReports,0);return '<h1 class="page-title">Reports</h1><div class="panel" id="reportBox">Loading...</div>'};async function loadReports(){const b=document.getElementById('reportBox');if(!b)return;const j=await F('/api/admin/reports');b.innerHTML='<div class="cards">'+Object.entries(j.summary||{}).map(([k,v])=>`<div class="stat"><label>${E(k)}</label><strong>${typeof v==='number'&&['deposit','withdrawal'].includes(k)?'৳'+v.toFixed(2):E(v)}</strong></div>`).join('')+'</div>'};
window.adminAudit=function(){setTimeout(loadAudit,0);return '<h1 class="page-title">Audit Log</h1><div class="panel" id="auditBox">Loading...</div>'};async function loadAudit(){const b=document.getElementById('auditBox');if(!b)return;const j=await F('/api/admin/audit-log');b.innerHTML=(j.logs||[]).map(x=>`<div class="item"><b>${E(x.action)}</b> • ${E(x.target)}<div>${E(JSON.stringify(x.detail))}</div><small>${E(x.created_at)}</small></div>`).join('')||'<p>No audit records.</p>'};
window.adminRoles=function(){setTimeout(loadRoles,0);return '<h1 class="page-title">Admin Roles & Permissions</h1><div class="panel" id="rolesBox">Loading...</div>'};async function loadRoles(){const b=document.getElementById('rolesBox');if(!b)return;const j=await F('/api/admin/roles');b.innerHTML=(j.roles||[]).map(x=>`<div class="item"><b>${E(x.name)}</b><div>${E((x.permissions||[]).join(', '))}</div></div>`).join('')};
window.adminBanners=function(){setTimeout(loadBanners,0);return '<h1 class="page-title">Banner Management</h1><div class="panel"><input id="bnTitle" placeholder="Title"><input id="bnImage" placeholder="Image URL / data URL"><input id="bnLink" placeholder="Link"><button class="btn green" onclick="addBanner()">Add Banner</button><div id="bnBox">Loading...</div></div>'};async function loadBanners(){const b=document.getElementById('bnBox');if(!b)return;const j=await F('/api/admin/banners');b.innerHTML=(j.banners||[]).map(x=>`<div class="item"><b>${E(x.title)}</b><div>${E(x.image)}</div><button class="btn red" onclick="delBanner('${E(x.id)}')">Delete</button></div>`).join('')};window.addBanner=async()=>{await F('/api/admin/banners',{method:'POST',body:JSON.stringify({title:bnTitle.value,image:bnImage.value,link:bnLink.value})});loadBanners()};window.delBanner=async id=>{await F('/api/admin/banners/'+id,{method:'DELETE'});loadBanners()};
window.adminFaqs=function(){setTimeout(loadFaqs,0);return '<h1 class="page-title">FAQ Management</h1><div class="panel"><input id="fqQ" placeholder="Question"><textarea id="fqA" placeholder="Answer"></textarea><button class="btn green" onclick="addFaq()">Add FAQ</button><div id="fqBox">Loading...</div></div>'};async function loadFaqs(){const b=document.getElementById('fqBox');if(!b)return;const j=await F('/api/admin/faqs');b.innerHTML=(j.faqs||[]).map(x=>`<div class="item"><b>${E(x.question)}</b><div>${E(x.answer)}</div></div>`).join('')};window.addFaq=async()=>{await F('/api/admin/faqs',{method:'POST',body:JSON.stringify({question:fqQ.value,answer:fqA.value})});loadFaqs()};
window.adminPages=function(){setTimeout(loadPages,0);return '<h1 class="page-title">Rules & Terms</h1><div class="panel"><textarea id="pgRules" placeholder="Rules"></textarea><textarea id="pgTerms" placeholder="Terms"></textarea><textarea id="pgPrivacy" placeholder="Privacy"></textarea><textarea id="pgDep" placeholder="Deposit Rules"></textarea><textarea id="pgWd" placeholder="Withdrawal Rules"></textarea><textarea id="pgRef" placeholder="Refund Rules"></textarea><button class="btn green" onclick="savePages()">Save Pages</button></div>'};async function loadPages(){const d=(await F('/api/admin/data')).data||{};const p=d.pages||{};pgRules.value=p.rules||'';pgTerms.value=p.terms||'';pgPrivacy.value=p.privacy||'';pgDep.value=p.deposit_rules||'';pgWd.value=p.withdrawal_rules||'';pgRef.value=p.refund_rules||''}window.savePages=async()=>{await F('/api/admin/pages',{method:'PUT',body:JSON.stringify({rules:pgRules.value,terms:pgTerms.value,privacy:pgPrivacy.value,deposit_rules:pgDep.value,withdrawal_rules:pgWd.value,refund_rules:pgRef.value})});alert('Saved')};
window.adminSupport=function(){setTimeout(loadAS,0);return '<h1 class="page-title">Support Management</h1><div class="panel" id="asBox">Loading...</div>'};async function loadAS(){const b=document.getElementById('asBox');if(!b)return;const j=await F('/api/admin/support');b.innerHTML=(j.messages||[]).map(x=>`<div class="item"><b>${E(x.user_code||x.user_id)} • ${E(x.sender)}</b><div>${E(x.message)}</div>${x.sender==='user'?`<button class="btn" onclick="replyAS('${E(x.user_id)}')">Reply</button>`:''}</div>`).join('')||'<p>No support messages.</p>'};window.replyAS=async id=>{const m=prompt('Reply');if(m)await F('/api/admin/support',{method:'POST',body:JSON.stringify({user_id:id,message:m})});loadAS()};
window.adminNotice=function(){return '<h1 class="page-title">Notifications / Notice</h1><div class="panel"><input id="ntTitle" placeholder="Title"><textarea id="ntMsg" placeholder="Message"></textarea><button class="btn green" onclick="sendNotice()">Send to all users</button></div>'};window.sendNotice=async()=>{await F('/api/admin/notice',{method:'POST',body:JSON.stringify({title:ntTitle.value,message:ntMsg.value})});alert('Notice sent')};
})();

window.adminWithdrawals=function(){setTimeout(loadAW,0);return '<h1 class="page-title">💰 Withdrawal Management</h1><p class="subtitle">Pending withdrawal review, approval/rejection and search.</p><div class="panel"><div class="toolbar"><input id="wdSearch" placeholder="Search user / account / withdrawal ID"><select id="wdStatus"><option value="all">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button class="btn blue" onclick="loadAW()">Refresh</button></div><div id="awStats" class="cards"></div><div id="awBox">Loading...</div></div>'};
async function loadAW(){const box=document.getElementById('awBox');if(!box)return;try{const st=document.getElementById('wdStatus')?.value||'all';const q=(document.getElementById('wdSearch')?.value||'').toLowerCase();const j=await F('/api/admin/withdrawals?status='+encodeURIComponent(st));let a=(j.withdrawals||[]).filter(x=>{const z=[x.id,x.user_code,x.phone,x.account_number,x.method,x.name].join(' ').toLowerCase();return !q||z.includes(q)});const counts={all:j.withdrawals?.length||0,pending:(j.withdrawals||[]).filter(x=>x.status==='pending').length,approved:(j.withdrawals||[]).filter(x=>x.status==='approved').length,rejected:(j.withdrawals||[]).filter(x=>x.status==='rejected').length};document.getElementById('awStats').innerHTML=Object.entries(counts).map(([k,v])=>'<div class="stat"><small>'+E(k.toUpperCase())+'</small><strong>'+v+'</strong></div>').join('');box.innerHTML=a.map(x=>'<div class="item" style="display:block"><b>#'+E(x.id)+' • '+E(x.user_code||'User')+' • ৳'+Number(x.amount||0).toFixed(2)+'</b><div>'+E(x.method||'')+' • '+E(x.account_number||'')+' • '+E(x.balance_type||'winning')+'</div><small class="muted">'+E(x.created_at||'')+' • '+E(x.status||'pending')+'</small>'+(x.note?'<div>Note: '+E(x.note)+'</div>':'')+(x.status==='pending'?'<div style="margin-top:10px"><button class="btn green" onclick="reviewAW(\''+E(x.id)+'\',\'approved\')">Approve</button> <button class="btn red" onclick="reviewAW(\''+E(x.id)+'\',\'rejected\')">Reject</button></div>':'')+'</div>').join('')||'<div class="empty">No withdrawals found.</div>'}catch(e){box.innerHTML='<div class="err">'+E(e.message)+'</div>'}}
window.reviewAW=async(id,status)=>{let note='';if(status==='rejected'){note=prompt('Reject reason','')??'';if(!note.trim())return}else if(!confirm('Approve this withdrawal?'))return;try{await F('/api/admin/withdrawals/'+encodeURIComponent(id)+'/review',{method:'POST',body:JSON.stringify({status,note})});toast(status==='approved'?'Withdrawal approved':'Withdrawal rejected');loadAW()}catch(e){toast(e.message)}};
window.adminWebsiteTools=function(){setTimeout(loadWT,0);return '<h1 class="page-title">🌐 Website Tools</h1><div class="panel"><h3>Banner Management</h3><div id="wtBanner"></div></div><div class="panel"><h3>FAQ Management</h3><div id="wtFaq"></div></div><div class="panel"><h3>Rules / Terms / Privacy</h3><div id="wtPages"></div></div><div class="panel"><h3>Audit Log</h3><div id="wtAudit"></div></div><div class="panel"><h3>Global Notice</h3><input id="wtNoticeTitle" placeholder="Title"><textarea id="wtNoticeMsg" placeholder="Message"></textarea><button class="btn green" onclick="sendWTNotice()">Send to all users</button></div></div>'};
async function loadWT(){try{const [b,f,d,a]=await Promise.all([F('/api/admin/banners'),F('/api/admin/faqs'),F('/api/admin/data'),F('/api/admin/audit-log')]);document.getElementById('wtBanner').innerHTML='<div class="toolbar"><input id="wtBT" placeholder="Banner title"><input id="wtBI" placeholder="Image URL / data URL"><input id="wtBL" placeholder="Link"><button class="btn green" onclick="addWTBanner()">Add Banner</button></div>'+(b.banners||[]).map(x=>'<div class="item"><b>'+E(x.title)+'</b><div>'+E(x.image)+'</div><button class="btn red" onclick="delWTBanner(\''+E(x.id)+'\')">Delete</button></div>').join('')||'<div class="empty">No banners</div>';document.getElementById('wtFaq').innerHTML='<div class="toolbar"><input id="wtFQ" placeholder="Question"><input id="wtFA" placeholder="Answer"><button class="btn green" onclick="addWTFaq()">Add FAQ</button></div>'+(f.faqs||[]).map(x=>'<div class="item"><b>'+E(x.question)+'</b><div>'+E(x.answer)+'</div></div>').join('')||'<div class="empty">No FAQs</div>';const pg=d.data?.pages||{};document.getElementById('wtPages').innerHTML='<textarea id="wtRules" placeholder="Rules">'+E(pg.rules||'')+'</textarea><textarea id="wtTerms" placeholder="Terms">'+E(pg.terms||'')+'</textarea><textarea id="wtPrivacy" placeholder="Privacy">'+E(pg.privacy||'')+'</textarea><button class="btn green" onclick="saveWTPages()">Save Pages</button>';document.getElementById('wtAudit').innerHTML=(a.logs||[]).slice(0,100).map(x=>'<div class="item"><b>'+E(x.action)+'</b> • '+E(x.target)+'<div>'+E(JSON.stringify(x.detail))+'</div><small>'+E(x.created_at)+'</small></div>').join('')||'<div class="empty">No audit logs</div>'}catch(e){toast(e.message)}}
window.addWTBanner=async()=>{await F('/api/admin/banners',{method:'POST',body:JSON.stringify({title:wtBT.value,image:wtBI.value,link:wtBL.value,enabled:true})});loadWT()};window.delWTBanner=async id=>{await F('/api/admin/banners/'+encodeURIComponent(id),{method:'DELETE'});loadWT()};window.addWTFaq=async()=>{await F('/api/admin/faqs',{method:'POST',body:JSON.stringify({question:wtFQ.value,answer:wtFA.value,enabled:true})});loadWT()};window.saveWTPages=async()=>{await F('/api/admin/pages',{method:'PUT',body:JSON.stringify({rules:wtRules.value,terms:wtTerms.value,privacy:wtPrivacy.value})});toast('Pages saved')};window.sendWTNotice=async()=>{if(!wtNoticeMsg.value.trim())return toast('Message দিন');await F('/api/admin/notice',{method:'POST',body:JSON.stringify({title:wtNoticeTitle.value||'Notice',message:wtNoticeMsg.value})});toast('Notice sent');wtNoticeMsg.value=''};

window.dashboard=function(){setTimeout(async()=>{try{const j=await F('/api/admin/reports'),s=j.summary||{};const b=document.querySelector('.cards');if(b)b.innerHTML=Object.entries(s).map(([k,v])=>`<div class=\"stat\"><label>${E(k)}</label><strong>${['deposit','withdrawal'].includes(k)?'৳'+Number(v).toFixed(2):E(v)}</strong></div>`).join('')}catch{}},0);return '<h1 class=\"page-title\">Dashboard</h1><p class=\"subtitle\">Live system summary.</p><div class=\"cards\"><div class=\"stat\"><label>Loading</label><strong>...</strong></div></div>'};
